version: "3.7"

services:
  web-server:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./nginx_config:/etc/nginx/conf.d
    ports:
      - 8000:80
    networks:
      - covidhealp-backend

  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    networks:
      - covidhealp-backend

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: es01
    volumes:
      - covidhealp-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=es-covid-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - covidhealp-backend

  kibana:
    image: kibana:7.6.2
    networks:
      - covidhealp-backend
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  covidhealp-backend:
    name: covidhealp-backend

volumes:
  covidhealp-data:
    name: covidhealp-data